### ISSUE TITLE
Ability to symbolize MDLs

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#32]
Include a pull-down to choose which analytes are symbologized.

Provide a prompt saying "Pick an analyte to enable this function" 

White space in top-right would then display a legend potentially?

May be a 2-step choice: MDL may be dependent on the matrix (water/soil/air/etc.)

Starting point could also be 1) Choose analyte; 2) Manually provide numeric value and values above are x color/values below are y color

**Comment by tommckennon** [comment]
In both map views for lab results and sample locations, there's the cases where you can't see the different symbology for the sample points in the 2D view since they share the same lat/long location. Thus, in both cases/tabs the 2D view symbology won't work out. I began thinking about MDL values and sample point depths. At this time, the sample point depths have yet to be merged with MDL values. It sounds like in order to symbolize the sample point MDL values in the lab results, the depths need to be in the data set, and even then the MDL value symbology would only be viewable in a 3D view due to the shared lat/long values.

cc @tbock

**Comment by jlherring** [comment]
Cheryl would like to go a different direction w/ symbology. Any updates will be in new issues.
