### ISSUE TITLE
Select features using lasso

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#42]
Provide the ability to select features by drawing on the map. Then the table view would filter down to only those selected in the map.

**Comment by jlherring** [comment]
Appears to be working, but need a way to clear selections (whether the use selected from the map or table). Something like this:
![image](https://user-images.githubusercontent.com/17882165/88210967-fb94aa80-cc22-11ea-90c7-4775ffedc41a.png)

**Comment by jlherring** [comment]
@tommckennon  So is the table highlighting selected features when using the lasso? Or filtering down the results to only those selected?

If the table filters down, then #26 is not needed. If we are just selecting from the full table, then they do need to be highlighted.

**Comment by tommckennon** [comment]
@jlherring , the lasso on map points is filtering down the table to only those selected. I followed the above description, so that the table view filters down to only those selected in the map. #26 describes how when a map point is selected, to highlight the corresponding records in the table. Thus, I think we're good on  both fronts. I'll put them back into review once I have the clear button working for selections described in your feedback for this issue.

**Comment by jlherring** [comment]
Clear Map Selection button is good to go!
