### ISSUE TITLE
Review/update pagination

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#45]
Stakeholders requested to remove pagination, but this is not feasible given the large number of records for some projects.

Determine the maximum number of records the browser can return, and up the number of records per page accordingly.

**Comment by tommckennon** [comment]
Ag Grid looks to have a very non-limiting factor for loading a lot of records at once. It's an enterprise solution built to handle a lot of records, which is why I chose it. I didn't think it could handle hundreds of thousands of records at once, but upon testing locally, it looks like it has no issue with that. Thus, I will turn off pagination completely, since that was the originally client request.
